=== ChiragGadhvi/XML/Validation/DTD/dtd-elements.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (firstname,lastname,age?,hobbies+,songs*)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT hobbies (#PCDATA)>
<!ELEMENT songs (#PCDATA)>

=== ChiragGadhvi/XML/Validation/DTD/DTD_elements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "dtd-elements.dtd">
<employees>
    <employee>
        <firstname>Chirag</firstname>
        <lastname>Gadhvi</lastname>
        <age>19</age>
        <!-- <age>20</age> -->
        <hobbies>Drawing</hobbies>
        <songs>Until I found You</songs>
        <songs>Mood</songs>
        <songs>See you Again</songs>
    </employee>
    <employee>
        <firstname>Nayan</firstname>
        <lastname>Gadhvi</lastname>
        <age>19</age>
        <hobbies>Basketball</hobbies>
        <hobbies>Football</hobbies>
        <songs>Starboy</songs>
        <songs>Blue Eyes</songs>
    </employee>
</employees>
